spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app
    username: myolang
    password: alskdj
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false